In [1]:
import numpy as np
#빅 데이터의 수학적 과학적 계산을 위해 만들어진 라이브러리.
##반복문 없이 전체 데이터의 연산이 가능한 표준 수학 함수들을 제공.
#배열-같은 자료형의 값들이 연속적인 형태로 구성된 자료 구조로 대량의 데이터를 그룹으로 관리하고 계산하기 위해 사용!
import pandas as pd 

In [2]:
list1=[1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [3]:
arr=np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

#### 1차원 배열

In [7]:
arr=np.array([1,2,3.5,'무야호'])
arr

array(['1', '2', '3.5', '무야호'], dtype='<U32')

#### 2차원 배열

In [9]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.shape

(2, 4)

In [11]:
arr2.dtype
#32는 bit를 뜻한다 2^32
#int8 = 2^8, int32=2^32

dtype('int32')

In [14]:
arr2.ndim
#n차원 배열 확인.

2

In [22]:
arr3=np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3
8


In [23]:
arr_zeros=np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
arr_ones=np.ones((2,4,3))
arr_ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

# 특정값으로 배열 생성

In [27]:
arr_full=np.full((5,5),2)
arr_full

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [42]:
count=[]
for i in range(1,51):
    count.append(i)
    arr_list=np.array(count)
arr_list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [41]:
arr5=np.arange(1,51)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [43]:
arr6=np.arange(1,51,10)
arr6

array([ 1, 11, 21, 31, 41])

In [44]:
arr7=np.arange(1,51)
arr7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [47]:
arr7.reshape(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [53]:
arr8=np.array([1.2,2.3,3.4],dtype=np.int64)
arr8

array([1, 2, 3], dtype=int64)

In [55]:
arr9=np.array(['1','2','3'],dtype=np.int64)
arr9

array([1, 2, 3], dtype=int64)

In [62]:
arr10=np.random.rand(2,3)
arr10

array([[0.49100108, 0.73112841, 0.27761115],
       [0.27847541, 0.16353046, 0.02758866]])

In [72]:
arr11=np.random.randint(1,50,size=(2,20))
arr11

array([[31, 31, 37,  4, 41, 48, 19, 26,  2, 10, 22, 33, 19, 24, 18, 19,
        48, 34,  7, 13],
       [27, 25, 14, 29, 33,  8, 29, 15, 13, 40, 39, 37, 30, 23, 25, 15,
        46, 14, 25, 22]])

# array 연산

In [74]:
arr12=np.array([[1,2],[3,4]])
arr12

array([[1, 2],
       [3, 4]])

# numpy 배열 인덱싱

In [75]:
arr16=np.array([[1,2,3],[4,5,6]])
arr16

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
arr16[0]

array([1, 2, 3])

# numpy 슬라이싱
- 배열의 범위를 지정하여 여러개의 데이터를 가져옴.

In [77]:
arr17=np.arange(10)
arr17

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr17[3:8]

array([3, 4, 5, 6, 7])

In [86]:
arr18=np.arange(1,51).reshape(5,10)
arr18

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [89]:
for i in arr18:
    print(i[1])

2
12
22
32
42


In [94]:
arr18[0:2, 2:5]


array([[ 3,  4,  5],
       [13, 14, 15]])

In [97]:
arr18[ : , 0]

array([ 1, 11, 21, 31, 41])

In [98]:
arr18[:, :2]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42]])

In [100]:
arr18[:4,:5]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [101]:
arr19=np.arange(1,19).reshape(3,6)
arr19

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [105]:
arr19[1:,[1,3,5]]

array([[ 8, 10, 12],
       [14, 16, 18]])

In [106]:
arr19[1:,1: :2]

array([[ 8, 10, 12],
       [14, 16, 18]])

In [107]:
arr19

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [108]:
arr19.T

array([[ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17],
       [ 6, 12, 18]])